import 'package:resumepad/utility/color_utility.dart';

const NAVIGATE_TO_PROFILE_TAB = 0;
const NAVIGATE_TO_PROFILE_SUMMARY_TAB = 1;
const NAVIGATE_TO_CONTACT_TAB = 2;
const NAVIGATE_TO_EDUCATION_TAB = 3;
const NAVIGATE_TO_EXPERIENCE_TAB = 4;
const NAVIGATE_TO_PROJECTS_TAB = 5;
const NAVIGATE_TO_REFERENCES_TAB = 7;
const NAVIGATE_TO_SKILLS_TAB = 6;
const NAVIGATE_TO_LANGUAGE_TAB = 8;
const NAVIGATE_TO_ALL_DONE_TAB = 9;

const SELECTED_THEME = 'SELECTED_THEME';
const SELECTED_THEME_RED = 0;
const SELECTED_THEME_BLUE = 1;
const SELECTED_THEME_GREEN = 2;
const SELECTED_THEME_YELLOW = 3;
const SELECTED_THEME_DARK = 3;
